import NewsletterOptin from '@/components/NewsletterBox';
import PostList from '@/components/PostList';
import { allPosts } from '@/constants/posts';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <>
      <NewsletterOptin />
      <PostList posts={allPosts} />
    </>
  );
}
